var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-_t1_m._.js")
R.c("server/chunks/ssr/1vx6_next_dist_0jae87t._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1r_-rv2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06fsrj-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j03a2-._.js")
R.c("server/chunks/ssr/1vx6_next_dist_client_components_09sla-b._.js")
R.c("server/chunks/ssr/1vx6_next_dist_client_components_builtin_forbidden_093tcwx.js")
R.c("server/chunks/ssr/1vx6_next_dist_client_components_builtin_unauthorized_1-jt_pe.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0pt47yr.js")
R.m(31088)
module.exports=R.m(31088).exports
